### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by armintabari** [kayzhu/LSHash#11]
I am trying to install this package. when I run pipe install it gives me this error:

pip install lshash==0.0.4dev
Collecting lshash==0.0.4dev
  Using cached lshash-0.0.4dev.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/3y/98pmr_g51g988x_v957qmh100000gn/T/pip-build-vgvzxrjr/lshash/setup.py", line 3, in <module>
        import lshash
      File "/private/var/folders/3y/98pmr_g51g988x_v957qmh100000gn/T/pip-build-vgvzxrjr/lshash/lshash/**init**.py", line 12, in <module>
        from lshash import LSHash
    ImportError: cannot import name 'LSHash'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3y/98pmr_g51g988x_v957qmh100000gn/T/pip-build-vgvzxrjr/lshash

**Comment by liyanbei1234** [comment]
the package "lshash" matches a lower version of python.if you want to use this with a higher version of python.
You can try to use the command as following to install this package:
"pip install lshash3"
I had solved the problem in this way

**Comment by cheeregofor** [comment]
> the package "lshash" matches a lower version of python.if you want to use this with a higher version of python.
> You can try to use the command as following to install this package:
> "pip install lshash3"
> I had solved the problem in this way

which version is your python?
